spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teorganizadb
    username: postgres
    password: 'password # Please change this for production'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: classpath:db/migration/postgresql